from __future__ import annotations

from typing import Dict, List

from ams.core.profiles.base import (
    AggregationMode,
    BehavioralRule,
    ProfileSpec,
    RequiredAPIRule,
    RequiredCSSRule,
    RequiredHTMLRule,
    RequiredJSRule,
    RequiredPHPRule,
    RequiredSQLRule,
)

def _build_html_profile_specs() -> Dict[str, object]:
    # HTML Rules - Expanded with comprehensive web development criteria
    # Weights are normalised so that the total = 1.0 for the HTML component.
    # Categories: Structure, Metadata, Semantic, Interactive/Forms, Accessibility
    """Build the html profile specs."""
    html_rules = [
        # STRUCTURE (0.26 total).
        RequiredHTMLRule(
            id="html.has_doctype",
            description="Document begins with a valid DOCTYPE declaration",
            selector="!doctype",
            min_count=1,
            weight=0.08,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="DOCTYPE is binary - either present or not. No partial credit.",
        ),
        RequiredHTMLRule(
            id="html.has_html_tag",
            description="Document has a root <html> element",
            selector="html",
            min_count=1,
            weight=0.06,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Root element is binary - either present or not.",
        ),
        RequiredHTMLRule(
            id="html.has_head",
            description="Document includes a <head> section",
            selector="head",
            min_count=1,
            weight=0.06,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Head section is binary - either present or not.",
        ),
        RequiredHTMLRule(
            id="html.has_body",
            description="Document includes a <body> section",
            selector="body",
            min_count=1,
            weight=0.06,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Body section is binary - either present or not.",
        ),
        # METADATA (0.16 total).
        RequiredHTMLRule(
            id="html.has_title",
            description="Document has a <title> element in the head",
            selector="title",
            min_count=1,
            weight=0.06,
            category="Metadata",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if title exists but is empty or generic (e.g., 'Untitled').",
        ),
        RequiredHTMLRule(
            id="html.has_meta_charset",
            description="Document specifies character encoding via <meta charset>",
            selector="meta_charset",
            min_count=1,
            weight=0.05,
            category="Metadata",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Charset declaration is binary - either present or not.",
        ),
        RequiredHTMLRule(
            id="html.has_meta_viewport",
            description="Document includes a viewport meta tag for responsive design",
            selector="meta_viewport",
            min_count=1,
            weight=0.05,
            category="Metadata",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if viewport exists but has suboptimal settings.",
        ),
        # SEMANTIC HTML (0.18 total).
        RequiredHTMLRule(
            id="html.has_semantic_structure",
            description="Uses semantic container elements (header, nav, main, section, article, aside, footer)",
            selector="semantic",
            min_count=1,
            weight=0.08,
            category="Semantics",
            partial_allowed=True,
            partial_range=(0.0, 0.75),
            severity="medium",
            llm_guidance="Award partial based on variety of semantic tags used. Full credit for 3+ different semantic elements.",
        ),
        RequiredHTMLRule(
            id="html.has_heading_hierarchy",
            description="Uses heading elements (h1-h6) for content hierarchy",
            selector="heading",
            min_count=1,
            weight=0.06,
            category="Semantics",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if headings exist but hierarchy is broken (e.g., h1 followed by h3).",
        ),
        RequiredHTMLRule(
            id="html.has_lists",
            description="Uses list elements (ul, ol, or dl) for structured content",
            selector="list",
            min_count=1,
            weight=0.04,
            category="Semantics",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="List usage is binary - either present or not.",
        ),
        # INTERACTIVE / FORMS (0.26 total).
        RequiredHTMLRule(
            id="html.has_form",
            description="Page includes at least one <form> element",
            selector="form",
            min_count=1,
            weight=0.08,
            category="Forms",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Form presence is binary - either present or not.",
        ),
        RequiredHTMLRule(
            id="html.has_input",
            description="Page includes at least one <input> element",
            selector="input",
            min_count=1,
            weight=0.06,
            category="Forms",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial based on input variety (text, email, password, etc.).",
        ),
        RequiredHTMLRule(
            id="html.has_labels",
            description="Form controls have associated <label> elements",
            selector="label",
            min_count=1,
            weight=0.08,
            category="Accessibility",
            partial_allowed=True,
            partial_range=(0.0, 0.75),
            severity="high",
            llm_guidance="Award partial based on percentage of inputs with associated labels.",
        ),
        RequiredHTMLRule(
            id="html.has_link",
            description="Page includes at least one anchor <a> element",
            selector="a",
            min_count=1,
            weight=0.04,
            category="Forms",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Link presence is binary - either present or not.",
        ),
        # ACCESSIBILITY (0.14 total).
        RequiredHTMLRule(
            id="html.has_alt_attributes",
            description="All <img> elements include meaningful alt attributes",
            selector="img_alt",
            min_count=1,
            weight=0.08,
            category="Accessibility",
            partial_allowed=True,
            partial_range=(0.0, 0.75),
            severity="high",
            llm_guidance="Award partial based on percentage of images with meaningful alt text. Empty alt='' for decorative images is acceptable.",
        ),
        RequiredHTMLRule(
            id="html.has_lang_attribute",
            description="The <html> element specifies a lang attribute",
            selector="html_lang",
            min_count=1,
            weight=0.06,
            category="Accessibility",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Lang attribute is binary - either present or not.",
        ),
        # ASSETS / LINKAGE (0.04 total, weights trimmed from structure rules).
        RequiredHTMLRule(
            id="html.links_stylesheet",
            description="Page links to an external stylesheet via <link rel='stylesheet'>",
            selector="link_stylesheet",
            min_count=1,
            weight=0.04,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Stylesheet linkage is binary - either present or not.",
        ),
        RequiredHTMLRule(
            id="html.links_script_or_js",
            description="Page includes JavaScript execution path via <script> tag",
            selector="link_script",
            min_count=0,
            weight=0.02,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Script linkage is optional. Award if present.",
        ),
        # CONTENT ELEMENTS (optional - bonus if used).
        RequiredHTMLRule(
            id="html.has_table",
            description="Page uses table markup when tabular content is expected",
            selector="table",
            min_count=0,
            weight=0.02,
            category="Content",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Table usage is optional. Award if present.",
        ),
        RequiredHTMLRule(
            id="html.has_image",
            description="Page uses image elements when visual content is expected",
            selector="img",
            min_count=0,
            weight=0.02,
            category="Content",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Image usage is optional. Award if present.",
        ),
    ]
    return {"html_rules": html_rules}


def _build_css_profile_specs() -> Dict[str, object]:
    # CSS Rules - Expanded with comprehensive web development criteria
    # Weights are normalised so that the total = 1.0 for the CSS component.
    # Categories: Structure, selectors, layout, styling, responsiveness.
    """Build the css profile specs."""
    css_rules = [
        # STRUCTURE (0.14 total).
        RequiredCSSRule(
            id="css.has_rule_block",
            description="Stylesheet contains at least one CSS rule block",
            needle="{",
            min_count=1,
            weight=0.08,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Rule block presence is binary - either present or not.",
        ),
        RequiredCSSRule(
            id="css.has_multiple_rules",
            description="Stylesheet contains multiple style rules (3+)",
            needle="multiple_rules",
            min_count=3,
            weight=0.06,
            category="Structure",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if 1-2 rules exist. Full credit for 3+.",
        ),
        # SELECTORS (0.20 total).
        RequiredCSSRule(
            id="css.has_class_selector",
            description="Uses class selectors for reusable styling",
            needle=".",
            min_count=1,
            weight=0.10,
            category="Selectors",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Class selector usage is binary.",
        ),
        RequiredCSSRule(
            id="css.has_id_selector",
            description="Uses ID selectors for unique elements",
            needle="#",
            min_count=0,
            weight=0.04,
            category="Selectors",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="ID selector is optional. Award if present.",
        ),
        RequiredCSSRule(
            id="css.has_element_selector",
            description="Uses element/type selectors (body, h1, p, etc.)",
            needle="element_selector",
            min_count=1,
            weight=0.06,
            category="Selectors",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Element selector usage is binary.",
        ),
        # LAYOUT (0.24 total).
        RequiredCSSRule(
            id="css.has_layout",
            description="Uses layout properties (margin, padding, display, position)",
            needle="layout",
            min_count=1,
            weight=0.10,
            category="Layout",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial based on variety of layout properties used.",
        ),
        RequiredCSSRule(
            id="css.has_flexbox",
            description="Uses Flexbox for flexible layout",
            needle="flexbox",
            min_count=1,
            weight=0.08,
            category="Layout",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if flex is declared but not fully utilized.",
        ),
        RequiredCSSRule(
            id="css.has_grid",
            description="Uses CSS Grid for grid-based layout",
            needle="grid",
            min_count=0,
            weight=0.06,
            category="Layout",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Grid is optional. Award if present.",
        ),
        # STYLING (0.16 total).
        RequiredCSSRule(
            id="css.has_color",
            description="Defines color and background properties",
            needle="color:",
            min_count=0,
            weight=0.08,
            category="Styling",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Color usage is binary.",
        ),
        RequiredCSSRule(
            id="css.has_typography",
            description="Uses typography properties (font-family, font-size)",
            needle="typography",
            min_count=1,
            weight=0.08,
            category="Styling",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial based on typography property variety.",
        ),
        # RESPONSIVENESS (0.16 total).
        RequiredCSSRule(
            id="css.has_media_query",
            description="Uses media queries for responsive design",
            needle="@media",
            min_count=1,  # Changed from 0 to require at least one media query
            weight=0.16,
            category="Responsiveness",
            partial_allowed=True,
            partial_range=(0.0, 0.75),
            severity="high",
            llm_guidance="Award partial based on media query coverage. Full credit for multiple breakpoints.",
            visual_check=True,  # Phase 3: Enable vision-based responsiveness check
        ),
        # MAINTAINABILITY (0.10 total).
        RequiredCSSRule(
            id="css.has_custom_properties",
            description="Uses CSS custom properties (variables) for maintainability",
            needle="custom_properties",
            min_count=0,
            weight=0.06,
            category="Maintainability",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Custom properties are optional. Award if present.",
        ),
        RequiredCSSRule(
            id="css.has_comments",
            description="Includes comments for code documentation",
            needle="comments",
            min_count=0,
            weight=0.04,
            category="Maintainability",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Comments are optional. Award if present.",
        ),
        # QUALITY / RESET (new generic rules).
        RequiredCSSRule(
            id="css.has_universal_reset",
            description="Applies a universal CSS reset or box-sizing strategy",
            needle="universal_reset",
            min_count=0,
            weight=0.04,
            category="Reset",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Universal reset is optional. Award if * selector or explicit reset strategy is present.",
        ),
        RequiredCSSRule(
            id="css.parses_cleanly",
            description="CSS is syntactically valid with balanced braces",
            needle="parses_cleanly",
            min_count=1,
            weight=0.06,
            category="Quality",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award 0.5 for minor brace imbalance (1-2 unmatched). 0 for severely broken CSS.",
        ),
    ]

    # CSS lab rules for visual and design-intent checks.
    # These rules are only required by the frontend_css_lab profile.
    css_lab_rules = list(css_rules) + [
        RequiredCSSRule(
            id="css.body_card_layout",
            description="Body or main container uses card-like layout (max-width, centred, padding, shadow, radius)",
            needle="body_card_layout",
            min_count=1,
            weight=0.10,
            category="Layout",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for max-width + margin:auto + padding + box-shadow + border-radius. Partial for 2-3 of these traits.",
        ),
        RequiredCSSRule(
            id="css.h1_styled",
            description="Main heading (h1) has non-default colour and size styling",
            needle="h1_styled",
            min_count=1,
            weight=0.08,
            category="Typography",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for colour + size + alignment. Partial for one or two of these.",
        ),
        RequiredCSSRule(
            id="css.table_profile_layout",
            description="Table element has width, spacing, or centering applied",
            needle="table_profile_layout",
            min_count=0,
            weight=0.06,
            category="Layout",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="low",
            llm_guidance="Award for table with max-width/width + margin or border-spacing. Optional if no table in task.",
        ),
        RequiredCSSRule(
            id="css.image_rounding_shadow",
            description="Images use border-radius (circular/rounded) and box-shadow",
            needle="image_rounding_shadow",
            min_count=0,
            weight=0.06,
            category="Styling",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="low",
            llm_guidance="Full credit for both border-radius + box-shadow. Partial for one.",
        ),
        RequiredCSSRule(
            id="css.h2_section_style",
            description="Section headings (h2) have colour and size styling",
            needle="h2_section_style",
            min_count=1,
            weight=0.06,
            category="Typography",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for colour + size + spacing. Partial for one or two.",
        ),
        RequiredCSSRule(
            id="css.list_readability_style",
            description="List elements (ul/li) have custom bullets or spacing for readability",
            needle="list_readability_style",
            min_count=0,
            weight=0.06,
            category="Styling",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="low",
            llm_guidance="Award for list-style + spacing on ul or li. Optional if no lists in task.",
        ),
        RequiredCSSRule(
            id="css.link_hover_style",
            description="Links have a distinct hover state (underline or colour change)",
            needle="link_hover_style",
            min_count=1,
            weight=0.08,
            category="Interaction",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for clear hover + normal state differentiation. Partial for hover only or very subtle change.",
        ),
    ]
    return {"css_rules": css_rules, "css_lab_rules": css_lab_rules}


def _build_js_profile_specs() -> Dict[str, object]:
    # JavaScript Rules - Expanded with comprehensive web development criteria
    # Weights are normalised so that the total = 1.0 for the JS component.
    # Categories: Events, DOM, functions, control flow, validation, async, errors.
    """Build the js profile specs."""
    js_rules = [
        # EVENTS (0.12 total).
        RequiredJSRule(
            id="js.has_event_listener",
            description="Registers event listeners for user interaction",
            needle="addeventlistener",
            min_count=1,
            weight=0.12,
            category="Events",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Award partial if inline event handlers (onclick) are used instead of addEventListener.",
        ),
        # DOM (0.20 total).
        RequiredJSRule(
            id="js.has_dom_query",
            description="Queries DOM elements (querySelector, getElementById, etc.)",
            needle="dom_query",
            min_count=1,
            weight=0.10,
            category="DOM",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="DOM query usage is binary.",
        ),
        RequiredJSRule(
            id="js.has_dom_manipulation",
            description="Manipulates DOM content (innerHTML, textContent, appendChild, etc.)",
            needle="dom_manipulation",
            min_count=1,
            weight=0.10,
            category="DOM",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Award partial based on variety and appropriateness of DOM manipulation methods.",
        ),
        # FUNCTIONS (0.16 total).
        RequiredJSRule(
            id="js.has_functions",
            description="Defines reusable functions",
            needle="function ",
            min_count=1,
            weight=0.10,
            category="Functions",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Function definition is binary.",
        ),
        RequiredJSRule(
            id="js.has_arrow_functions",
            description="Uses arrow function syntax",
            needle="=>",
            min_count=0,
            weight=0.06,
            category="Modern Practices",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Arrow functions are optional. Award if present.",
        ),
        # CONTROL FLOW (0.14 total).
        RequiredJSRule(
            id="js.has_conditionals",
            description="Uses conditional statements (if/else, switch)",
            needle="if ",
            min_count=1,
            weight=0.08,
            category="Control Flow",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Conditional usage is binary.",
        ),
        RequiredJSRule(
            id="js.has_loops",
            description="Uses loops (for, while, forEach)",
            needle="loops",
            min_count=0,
            weight=0.06,
            category="Control Flow",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Loop usage is optional. Award if present.",
        ),
        # VALIDATION (0.08 total).
        RequiredJSRule(
            id="js.has_form_validation",
            description="Validates form input or user data",
            needle="form_validation",
            min_count=0,
            weight=0.08,
            category="Validation",
            partial_allowed=True,
            partial_range=(0.0, 0.75),
            severity="medium",
            llm_guidance="Award partial based on validation coverage and robustness.",
        ),
        # ASYNC (0.08 total).
        RequiredJSRule(
            id="js.has_async_patterns",
            description="Uses async patterns (async/await, fetch, Promise)",
            needle="async_patterns",
            min_count=0,
            weight=0.08,
            category="Async",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if callbacks are used instead of modern async/await.",
        ),
        # ERROR HANDLING (0.08 total).
        RequiredJSRule(
            id="js.has_error_handling",
            description="Includes error handling (try-catch)",
            needle="try",
            min_count=0,
            weight=0.08,
            category="Error Handling",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Error handling usage is optional. Award if present.",
        ),
        # MODERN JS (0.14 total).
        RequiredJSRule(
            id="js.has_const_let",
            description="Uses modern variable declarations (const/let)",
            needle="const_let",
            min_count=1,
            weight=0.08,
            category="Modern Practices",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial if let is used but const is not for constants.",
        ),
        RequiredJSRule(
            id="js.has_template_literals",
            description="Uses template literals for string formatting",
            needle="`",
            min_count=0,
            weight=0.06,
            category="Modern Practices",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Template literals are optional. Award if present.",
        ),
    ]

    # JavaScript calculator rules for DOM and logic checks.
    # Only required by the frontend_calculator profile.
    js_calculator_rules = list(js_rules) + [
        RequiredJSRule(
            id="js.creates_display_dom",
            description="JavaScript creates or references the calculator display (input#theDisplay)",
            needle="creates_display_dom",
            min_count=1,
            weight=0.08,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Full credit for getElementById('theDisplay') or createElement of display input. Partial for display element referenced but not explicitly created.",
        ),
        RequiredJSRule(
            id="js.creates_digit_buttons",
            description="JavaScript creates digit buttons (0-9, decimal, equals) dynamically",
            needle="creates_digit_buttons",
            min_count=1,
            weight=0.06,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Full credit for all 12 digit/decimal/equals buttons. Partial for 4-7 digit buttons.",
        ),
        RequiredJSRule(
            id="js.creates_operator_buttons",
            description="JavaScript creates operator buttons (+, -, *, /)",
            needle="creates_operator_buttons",
            min_count=1,
            weight=0.06,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Full credit for all 4 operators. Partial for 2-3.",
        ),
        RequiredJSRule(
            id="js.has_updateDisplay",
            description="Function or logic appends clicked value to the calculator display",
            needle="has_updatedisplay",
            min_count=1,
            weight=0.08,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Full credit for updateDisplay function or equivalent display.value += pattern. Partial for partially correct logic.",
        ),
        RequiredJSRule(
            id="js.has_prevalue_preop_state",
            description="Tracks previous value (preValue) and previous operator (preOp) for chained calculations",
            needle="has_prevalue_preop",
            min_count=1,
            weight=0.08,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Full credit for explicit preValue + preOp state. Partial for equivalent state tracking without those names.",
        ),
        RequiredJSRule(
            id="js.has_doCalc",
            description="Performs the stored arithmetic operation (doCalc function or equivalent)",
            needle="has_docalc",
            min_count=1,
            weight=0.08,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Full credit for doCalc function handling all 4 operations. Partial for 2-3 operations handled.",
        ),
        RequiredJSRule(
            id="js.clears_or_updates_display_correctly",
            description="Operator press clears the display; equals shows the result",
            needle="clears_display",
            min_count=1,
            weight=0.06,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for both clear-on-operator and result-on-equals. Partial for one only.",
        ),
        RequiredJSRule(
            id="js.uses_createElement",
            description="Uses document.createElement() for dynamic DOM construction",
            needle="uses_createelement",
            min_count=1,
            weight=0.06,
            category="Modern Practices",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="createElement usage is binary in the calculator context.",
        ),
        RequiredJSRule(
            id="js.avoids_document_write",
            description="Does not rely on document.write() for UI construction",
            needle="avoids_document_write",
            min_count=1,
            weight=0.06,
            category="Modern Practices",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for no document.write. Partial for minimal leftover non-core use.",
        ),
        RequiredJSRule(
            id="js.extra_features",
            description="Implements optional calculator extras (clear, sqrt, percentage, memory, etc.)",
            needle="extra_features",
            min_count=0,
            weight=0.04,
            category="Calculator",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="low",
            llm_guidance="Award for one or more working extras. Partial for attempted but broken extras.",
        ),
    ]
    return {"js_rules": js_rules, "js_calculator_rules": js_calculator_rules}


def _build_php_profile_specs() -> Dict[str, object]:
    # PHP Rules - Expanded with comprehensive web development criteria
    # Weights are normalised so that the total = 1.0 for the PHP component.
    # Categories: Structure, input, output, database, sessions, functions, errors.
    """Build the php profile specs."""
    php_rules_fullstack = [
        # STRUCTURE (0.06 total).
        RequiredPHPRule(
            id="php.has_open_tag",
            description="PHP file contains opening tag",
            needle="<?php",
            min_count=1,
            weight=0.06,
            category="Structure",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="PHP opening tag is binary.",
        ),
        # INPUT HANDLING (0.20 total).
        RequiredPHPRule(
            id="php.uses_request",
            description="Uses request superglobals ($_GET, $_POST, $_REQUEST)",
            needle="request_superglobal",
            min_count=1,
            weight=0.10,
            category="Input",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Request superglobal usage is binary.",
        ),
        RequiredPHPRule(
            id="php.has_validation",
            description="Validates input (isset, empty, filter_var)",
            needle="validation",
            min_count=1,
            weight=0.10,
            category="Validation",
            partial_allowed=True,
            partial_range=(0.0, 0.75),
            severity="high",
            llm_guidance="Award partial based on depth and coverage of validation logic.",
        ),
        # SECURITY (0.10 total).
        RequiredPHPRule(
            id="php.has_sanitisation",
            description="Sanitises output (htmlspecialchars, htmlentities, strip_tags)",
            needle="sanitisation",
            min_count=0,
            weight=0.10,
            category="Security",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Award partial if some but not all output is sanitised.",
        ),
        # OUTPUT (0.08 total).
        RequiredPHPRule(
            id="php.outputs",
            description="Outputs content (echo, print)",
            needle="output",
            min_count=1,
            weight=0.08,
            category="Output",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Output usage is binary.",
        ),
        # DATABASE (0.26 total).
        RequiredPHPRule(
            id="php.uses_database",
            description="Interacts with database (mysqli, PDO)",
            needle="database",
            min_count=0,
            weight=0.16,
            category="Database",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Database interaction is optional. Award if present.",
        ),
        RequiredPHPRule(
            id="php.uses_prepared_statements",
            description="Uses prepared statements for SQL safety",
            needle="prepared_statements",
            min_count=0,
            weight=0.10,
            category="Security",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="high",
            llm_guidance="Award partial if some queries use prepared statements but not all.",
        ),
        # SESSIONS (0.08 total).
        RequiredPHPRule(
            id="php.uses_sessions",
            description="Uses session handling (session_start, $_SESSION)",
            needle="sessions",
            min_count=0,
            weight=0.08,
            category="Sessions",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Session usage is optional. Award if present.",
        ),
        # FUNCTIONS (0.06 total).
        RequiredPHPRule(
            id="php.has_functions",
            description="Defines reusable functions",
            needle="function ",
            min_count=0,
            weight=0.06,
            category="Functions",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Function definition is optional. Award if present.",
        ),
        # CONTROL FLOW (0.10 total).
        RequiredPHPRule(
            id="php.has_conditionals",
            description="Uses conditional statements (if/else, switch)",
            needle="if ",
            min_count=1,
            weight=0.06,
            category="Control Flow",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Conditional usage is binary.",
        ),
        RequiredPHPRule(
            id="php.has_loops",
            description="Uses loops (for, while, foreach)",
            needle="loops",
            min_count=0,
            weight=0.04,
            category="Control Flow",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Loop usage is optional. Award if present.",
        ),
        # ERROR HANDLING (0.06 total).
        RequiredPHPRule(
            id="php.has_error_handling",
            description="Includes error handling (try-catch, error_reporting)",
            needle="error_handling",
            min_count=0,
            weight=0.06,
            category="Error Handling",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Error handling is optional. Award if present.",
        ),
        # RESPONSE PATH / ALIGNMENT (new generic checks).
        RequiredPHPRule(
            id="php.response_path_complete",
            description="Script has a complete request-receive-process-output path",
            needle="response_path_complete",
            min_count=1,
            weight=0.06,
            category="Architecture",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for input superglobal + conditional logic + output. Partial for partial path only.",
        ),
    ]
    return {"php_rules_fullstack": php_rules_fullstack}


def _build_sql_profile_specs() -> Dict[str, object]:
    # SQL Rules - Expanded with comprehensive database design criteria
    # Weights are normalised so that the total = 1.0 for the SQL component.
    # Categories: Schema, Constraints, CRUD, Queries, Advanced
    """Build the sql profile specs."""
    sql_rules_fullstack = [
        # SCHEMA (0.30 total).
        RequiredSQLRule(
            id="sql.has_create_table",
            description="Defines tables (CREATE TABLE)",
            needle="create table",
            min_count=1,
            weight=0.12,
            category="Schema",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Table creation is binary.",
        ),
        RequiredSQLRule(
            id="sql.has_primary_key",
            description="Defines primary keys for unique row identification",
            needle="primary key",
            min_count=1,
            weight=0.10,
            category="Schema",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="Primary key usage is binary.",
        ),
        RequiredSQLRule(
            id="sql.has_foreign_key",
            description="Defines foreign keys for referential integrity",
            needle="foreign_key",
            min_count=0,
            weight=0.08,
            category="Constraints",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="Foreign key is optional. Award if present.",
        ),
        # CONSTRAINTS (0.14 total).
        RequiredSQLRule(
            id="sql.has_constraints",
            description="Uses constraints (NOT NULL, UNIQUE, CHECK, DEFAULT)",
            needle="constraints",
            min_count=0,
            weight=0.08,
            category="Constraints",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial based on variety of constraints used.",
        ),
        RequiredSQLRule(
            id="sql.has_data_types",
            description="Specifies appropriate data types (INT, VARCHAR, TEXT, DATE)",
            needle="data_types",
            min_count=1,
            weight=0.06,
            category="Schema",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Award partial based on appropriateness of data types for column data.",
        ),
        # CRUD (0.32 total).
        RequiredSQLRule(
            id="sql.has_insert",
            description="Inserts data (INSERT INTO)",
            needle="insert into",
            min_count=1,
            weight=0.10,
            category="CRUD",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="INSERT usage is binary.",
        ),
        RequiredSQLRule(
            id="sql.has_select",
            description="Selects data (SELECT)",
            needle="select ",
            min_count=1,
            weight=0.12,
            category="CRUD",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="high",
            llm_guidance="SELECT usage is binary.",
        ),
        RequiredSQLRule(
            id="sql.has_update",
            description="Updates data (UPDATE)",
            needle="update ",
            min_count=0,
            weight=0.06,
            category="CRUD",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="UPDATE is optional. Award if present.",
        ),
        RequiredSQLRule(
            id="sql.has_delete",
            description="Deletes data (DELETE)",
            needle="delete ",
            min_count=0,
            weight=0.04,
            category="CRUD",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="DELETE is optional. Award if present.",
        ),
        # QUERIES (0.16 total).
        RequiredSQLRule(
            id="sql.has_where",
            description="Uses WHERE clauses for filtering",
            needle="where ",
            min_count=0,
            weight=0.08,
            category="Queries",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="WHERE usage is optional. Award if present.",
        ),
        RequiredSQLRule(
            id="sql.has_join",
            description="Uses JOIN operations for combining tables",
            needle="join ",
            min_count=0,
            weight=0.08,
            category="Queries",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="medium",
            llm_guidance="JOIN is optional. Award if present.",
        ),
        # ADVANCED (0.08 total).
        RequiredSQLRule(
            id="sql.has_aggregate",
            description="Uses aggregate functions (COUNT, SUM, AVG, GROUP BY)",
            needle="aggregate",
            min_count=0,
            weight=0.08,
            category="Queries",
            partial_allowed=False,
            partial_range=(0.0, 0.0),
            severity="low",
            llm_guidance="Aggregate functions are optional. Award if present.",
        ),
        # QUALITY.
        RequiredSQLRule(
            id="sql.parses_cleanly",
            description="SQL is syntactically valid with semicolons and balanced structure",
            needle="parses_cleanly",
            min_count=1,
            weight=0.06,
            category="Quality",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for valid SQL with semicolons. Partial for minor syntax issues.",
        ),
    ]

    # Behavioural Rules - Dynamic runtime testing criteria
    # Weights are normalised so that the total = 1.0 for the behavioural component.
    behavioral_rules_frontend = [
        BehavioralRule(
            id="behavior.page_loads",
            description="HTML page renders without errors in browser",
            test_type="page_load",
            component="html",
            weight=0.30,
        ),
        BehavioralRule(
            id="behavior.js_interactive",
            description="JavaScript responds to user events and modifies DOM",
            test_type="js_interaction",
            component="js",
            weight=0.40,
        ),
        BehavioralRule(
            id="behavior.hover_style_visible",
            description="Link hover state creates a visible style change in browser",
            test_type="hover_check",
            component="css",
            weight=0.15,
        ),
        BehavioralRule(
            id="behavior.responsive_resize",
            description="Layout remains structurally usable after viewport change (mobile/desktop)",
            test_type="viewport_resize",
            component="css",
            weight=0.15,
        ),
    ]

    behavioral_rules_fullstack = [
        BehavioralRule(
            id="behavior.page_loads",
            description="HTML page renders without errors in browser",
            test_type="page_load",
            component="html",
            weight=0.20,
        ),
        BehavioralRule(
            id="behavior.js_interactive",
            description="JavaScript responds to user events and modifies DOM",
            test_type="js_interaction",
            component="js",
            weight=0.20,
        ),
        BehavioralRule(
            id="behavior.form_submits",
            description="Form submission triggers PHP processing",
            test_type="form_submit",
            component="php",
            weight=0.30,
        ),
        BehavioralRule(
            id="behavior.db_persists",
            description="Database operations persist and retrieve data correctly",
            test_type="db_persist",
            component="sql",
            weight=0.30,
        ),
    ]

    behavioral_rules_api = [
        BehavioralRule(
            id="behavior.page_loads",
            description="HTML page renders without errors in browser",
            test_type="page_load",
            component="html",
            weight=0.25,
        ),
        BehavioralRule(
            id="behavior.js_interactive",
            description="JavaScript responds to user events and modifies DOM",
            test_type="js_interaction",
            component="js",
            weight=0.35,
        ),
        BehavioralRule(
            id="behavior.api_exec",
            description="API-backed flow returns a usable response",
            test_type="api_exec",
            component="api",
            weight=0.40,
        ),
    ]

    return {
        "sql_rules_fullstack": sql_rules_fullstack,
        "behavioral_rules_frontend": behavioral_rules_frontend,
        "behavioral_rules_fullstack": behavioral_rules_fullstack,
        "behavioral_rules_api": behavioral_rules_api,
    }


def _build_api_profile_specs() -> Dict[str, object]:
    """Build the api profile specs."""
    api_required_rules = [
        RequiredAPIRule(
            id="api.json_encode",
            description="Server-side script encodes responses as JSON",
            needle="json_encode",
            min_count=1,
            weight=1.5,
        ),
        RequiredAPIRule(
            id="api.json_content_type",
            description="Server-side script sets JSON Content-Type header",
            needle="application/json",
            min_count=1,
            weight=1.0,
        ),
        RequiredAPIRule(
            id="api.accepts_method",
            description="API handler checks or routes by HTTP request method",
            needle="accepts_method",
            min_count=1,
            weight=0.8,
            category="HTTP",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for explicit method routing. Partial for any method awareness.",
        ),
        RequiredAPIRule(
            id="api.valid_json_shape",
            description="JSON response has a meaningful structure (array or keyed object)",
            needle="valid_json_shape",
            min_count=1,
            weight=1.0,
            category="Response",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="medium",
            llm_guidance="Full credit for json_encode with array/object. Partial for bare variable encode.",
        ),
        RequiredAPIRule(
            id="api.http_status_codes",
            description="Uses appropriate HTTP status codes for success and error responses",
            needle="http_status_codes",
            min_count=0,
            weight=0.6,
            category="HTTP",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="low",
            llm_guidance="Award for http_response_code() or header() status codes. Optional.",
        ),
        RequiredAPIRule(
            id="api.error_response_path",
            description="Error conditions produce a structured JSON error response",
            needle="error_response_path",
            min_count=0,
            weight=0.6,
            category="Response",
            partial_allowed=True,
            partial_range=(0.0, 0.5),
            severity="low",
            llm_guidance="Award for json_encode inside if/catch with error key. Optional.",
        ),
    ]

    # Calculator-specific behavioural rules
    behavioral_rules_calculator = [
        BehavioralRule(
            id="behavior.calculator_sequence",
            description="Calculator correctly computes standard arithmetic sequences (2+3=5, 9-4=5, 6*7=42, 8/2=4)",
            test_type="calculator_sequence",
            component="js",
            weight=0.40,
        ),
        BehavioralRule(
            id="behavior.display_append",
            description="Clicking digits 1, 2, 3 sequentially shows 123 in the display",
            test_type="calculator_display",
            component="js",
            weight=0.30,
        ),
        BehavioralRule(
            id="behavior.operator_state_flow",
            description="Operator press stores state and clears display; equals shows result",
            test_type="calculator_operator",
            component="js",
            weight=0.30,
        ),
    ]

    return {
        "api_required_rules": api_required_rules,
        "behavioral_rules_calculator": behavioral_rules_calculator,
    }


def _build_profile_specs() -> Dict[str, ProfileSpec]:
    """Build the profile specs."""
    spec_parts: Dict[str, object] = {}
    spec_parts.update(_build_html_profile_specs())
    html_rules = spec_parts["html_rules"]
    spec_parts.update(_build_css_profile_specs())
    css_rules = spec_parts["css_rules"]
    css_lab_rules = spec_parts["css_lab_rules"]
    spec_parts.update(_build_js_profile_specs())
    js_rules = spec_parts["js_rules"]
    js_calculator_rules = spec_parts["js_calculator_rules"]
    spec_parts.update(_build_php_profile_specs())
    php_rules_fullstack = spec_parts["php_rules_fullstack"]
    spec_parts.update(_build_sql_profile_specs())
    sql_rules_fullstack = spec_parts["sql_rules_fullstack"]
    behavioral_rules_frontend = spec_parts["behavioral_rules_frontend"]
    behavioral_rules_fullstack = spec_parts["behavioral_rules_fullstack"]
    behavioral_rules_api = spec_parts["behavioral_rules_api"]
    spec_parts.update(_build_api_profile_specs())
    api_required_rules = spec_parts["api_required_rules"]
    behavioral_rules_calculator = spec_parts["behavioral_rules_calculator"]

    frontend_basic = ProfileSpec(
        name="frontend_basic",
        required_html=html_rules,
        required_css=css_rules,
        required_js=[],
        required_php=[],
        required_sql=[],
        behavioral_rules=[
            BehavioralRule(
                id="behavior.page_loads",
                description="Primary HTML page renders without errors in browser",
                test_type="page_load",
                component="html",
                weight=1.0,
            ),
        ],
        required_files=[".html"],
        relevant_artefacts=["html", "css"],
        optional_components=["js"],
        expected_layers=["html", "css", "js"],
        enabled_static_checks=["html", "css", "consistency"],
        enabled_behavioural_checks=["page_load"],
        enabled_browser_checks=["page_load"],
        enabled_layout_checks=["visibility"],
        expected_entrypoint_types=["html"],
        component_weights={"html": 0.55, "css": 0.45},
        missing_component_treatment={"html": "zero", "css": "zero", "js": "warning"},
        role_expectations={
            "primary_page": "single primary HTML page",
            "stylesheet_set": "linked stylesheet set",
        },
        frontend_only=True,
    )

    frontend_interactive = ProfileSpec(
        name="frontend_interactive",
        required_html=html_rules,
        required_css=css_rules,
        required_js=js_rules,
        required_php=[],
        required_sql=[],
        behavioral_rules=behavioral_rules_frontend,
        required_files=[".html"],
        relevant_artefacts=["html", "css", "js"],
        expected_layers=["html", "css", "js"],
        enabled_static_checks=["html", "css", "js", "consistency"],
        enabled_behavioural_checks=["page_load", "js_interaction"],
        enabled_browser_checks=["page_load", "interaction", "console"],
        enabled_layout_checks=["responsive", "visibility"],
        expected_entrypoint_types=["html"],
        component_weights={"html": 0.34, "css": 0.33, "js": 0.33},
        missing_component_treatment={"html": "zero", "css": "zero", "js": "zero"},
        role_expectations={
            "primary_page": "single primary HTML page",
            "secondary_page": "reachable linked pages",
            "stylesheet_set": "linked stylesheet set",
            "script_set": "linked script set",
        },
        frontend_only=True,
        aliases=("frontend",),
    )

    fullstack_form_php = ProfileSpec(
        name="fullstack_form_php",
        required_html=html_rules,
        required_css=css_rules,
        required_js=js_rules,
        required_php=php_rules_fullstack,
        required_sql=[],
        behavioral_rules=[
            rule
            for rule in behavioral_rules_fullstack
            if rule.id != "behavior.db_persists"
        ],
        required_files=[".html", ".php"],
        relevant_artefacts=["html", "css", "js", "php"],
        optional_components=["sql"],
        expected_layers=["html", "css", "js", "php"],
        enabled_static_checks=["html", "css", "js", "php", "consistency"],
        enabled_behavioural_checks=["page_load", "js_interaction", "form_submit"],
        enabled_browser_checks=["page_load", "interaction", "console"],
        enabled_layout_checks=["responsive", "visibility"],
        expected_entrypoint_types=["html", "php"],
        component_weights={"html": 0.25, "css": 0.2, "js": 0.2, "php": 0.35},
        missing_component_treatment={
            "html": "zero",
            "css": "zero",
            "js": "zero",
            "php": "zero",
            "sql": "warning",
        },
        role_expectations={
            "primary_page": "single primary HTML page",
            "backend_entrypoint": "form-processing PHP entrypoint",
            "script_set": "interactive scripts",
        },
        frontend_only=False,
    )

    fullstack_php_sql = ProfileSpec(
        name="fullstack_php_sql",
        required_html=html_rules,
        required_css=css_rules,
        required_js=js_rules,
        required_php=php_rules_fullstack,
        required_sql=sql_rules_fullstack,
        behavioral_rules=behavioral_rules_fullstack,
        required_files=[".html", ".php", ".sql"],
        relevant_artefacts=["html", "css", "js", "php", "sql"],
        expected_layers=["html", "css", "js", "php", "sql"],
        enabled_static_checks=["html", "css", "js", "php", "sql", "consistency"],
        enabled_behavioural_checks=["page_load", "js_interaction", "form_submit", "db_persist"],
        enabled_browser_checks=["page_load", "interaction", "console"],
        enabled_layout_checks=["responsive", "visibility"],
        expected_entrypoint_types=["html", "php", "sql"],
        component_weights={"html": 0.2, "css": 0.18, "js": 0.18, "php": 0.24, "sql": 0.2},
        missing_component_treatment={
            "html": "zero",
            "css": "zero",
            "js": "zero",
            "php": "zero",
            "sql": "zero",
        },
        role_expectations={
            "primary_page": "single primary HTML page",
            "backend_entrypoint": "reachable PHP entrypoint",
            "database_schema_file": "database/schema SQL file",
        },
        frontend_only=False,
        aliases=("fullstack",),
    )

    api_backed_web = ProfileSpec(
        name="api_backed_web",
        required_html=html_rules,
        required_css=css_rules,
        required_js=js_rules,
        required_php=[],
        required_sql=[],
        behavioral_rules=behavioral_rules_api,
        required_api=api_required_rules,
        required_files=[".html", ".js"],
        relevant_artefacts=["html", "css", "js", "api"],
        optional_components=["php", "sql"],
        expected_layers=["html", "css", "js", "api"],
        enabled_static_checks=["html", "css", "js", "api", "consistency"],
        enabled_behavioural_checks=["page_load", "js_interaction", "api_exec"],
        enabled_browser_checks=["page_load", "interaction", "console"],
        enabled_layout_checks=["responsive", "visibility"],
        expected_entrypoint_types=["html", "api"],
        component_weights={"html": 0.2, "css": 0.2, "js": 0.25, "api": 0.35},
        missing_component_treatment={
            "html": "zero",
            "css": "zero",
            "js": "zero",
            "api": "zero",
            "php": "warning",
            "sql": "warning",
        },
        role_expectations={
            "primary_page": "single primary HTML page",
            "script_set": "API client script set",
            "api_client_code": "API request/response flow",
        },
        frontend_only=False,
    )

    frontend_css_lab = ProfileSpec(
        name="frontend_css_lab",
        required_html=html_rules,
        required_css=css_lab_rules,
        required_js=js_rules,
        required_php=[],
        required_sql=[],
        behavioral_rules=behavioral_rules_frontend,
        required_files=[".html", ".css"],
        relevant_artefacts=["html", "css", "js"],
        optional_components=[],
        expected_layers=["html", "css", "js"],
        enabled_static_checks=["html", "css", "js", "consistency"],
        enabled_behavioural_checks=["page_load", "js_interaction", "hover_check", "viewport_resize"],
        enabled_browser_checks=["page_load", "interaction", "console", "computed_style", "extended_browser"],
        enabled_layout_checks=["responsive", "visibility", "computed_style"],
        expected_entrypoint_types=["html"],
        component_weights={"html": 0.30, "css": 0.45, "js": 0.25},
        missing_component_treatment={"html": "zero", "css": "zero", "js": "warning"},
        role_expectations={
            "primary_page": "single primary HTML page with profile layout",
            "stylesheet_set": "linked CSS stylesheet with visual design",
        },
        frontend_only=True,
        aliases=("css_lab",),
    )

    frontend_calculator = ProfileSpec(
        name="frontend_calculator",
        required_html=html_rules,
        required_css=css_rules,
        required_js=js_calculator_rules,
        required_php=[],
        required_sql=[],
        behavioral_rules=behavioral_rules_frontend + behavioral_rules_calculator,
        required_files=[".html", ".js"],
        relevant_artefacts=["html", "css", "js"],
        optional_components=[],
        expected_layers=["html", "css", "js"],
        enabled_static_checks=["html", "css", "js", "consistency"],
        enabled_behavioural_checks=[
            "page_load", "js_interaction",
            "calculator_sequence", "calculator_display", "calculator_operator",
        ],
        enabled_browser_checks=["page_load", "interaction", "console", "extended_browser"],
        enabled_layout_checks=["responsive", "visibility"],
        expected_entrypoint_types=["html"],
        component_weights={"html": 0.25, "css": 0.20, "js": 0.55},
        missing_component_treatment={"html": "zero", "css": "warning", "js": "zero"},
        role_expectations={
            "primary_page": "calculator HTML page",
            "script_set": "JavaScript calculator logic",
        },
        frontend_only=True,
        aliases=("calculator",),
    )

    specs = {
        spec.name: spec
        for spec in (
            frontend_basic,
            frontend_interactive,
            fullstack_form_php,
            fullstack_php_sql,
            api_backed_web,
            frontend_css_lab,
            frontend_calculator,
        )
    }
    return specs


PROFILE_SPECS = _build_profile_specs()
PROFILE_ALIASES = {
    alias: spec.name
    for spec in PROFILE_SPECS.values()
    for alias in spec.aliases
}
VISIBLE_PROFILE_SPECS = {
    name: spec for name, spec in PROFILE_SPECS.items()
}
