"""Centralised Finding ID constants."""
from __future__ import annotations


class HTML:
    """Finding IDs emitted by HTML assessors."""

    # Static assessor.
    MISSING_FILES = "HTML.MISSING_FILES"
    SKIPPED = "HTML.SKIPPED"
    READ_ERROR = "HTML.READ_ERROR"
    PARSE_OK = "HTML.PARSE_OK"
    PARSE_SUSPECT = "HTML.PARSE_SUSPECT"
    ELEMENT_EVIDENCE = "HTML.ELEMENT_EVIDENCE"
    QUALITY_INLINE_CSS = "HTML.QUALITY.INLINE_CSS"
    QUALITY_DEPRECATED_TAGS = "HTML.QUALITY.DEPRECATED_TAGS"

    # Required assessor.
    REQ_PASS = "HTML.REQ.PASS"
    REQ_FAIL = "HTML.REQ.FAIL"
    REQ_SKIPPED = "HTML.REQ.SKIPPED"
    REQ_MISSING_FILES = "HTML.REQ.MISSING_FILES"
    REQ_READ_ERROR = "HTML.REQ.READ_ERROR"

    # Behavioural.
    BEHAVIORAL_PAGE_LOADS = "HTML.BEHAVIORAL.PAGE_LOADS"
    BEHAVIORAL_FORM_EXISTS = "HTML.BEHAVIORAL.FORM_EXISTS"
    BEHAVIORAL_NO_FORM = "HTML.BEHAVIORAL.NO_FORM"
    BEHAVIORAL_NO_BODY = "HTML.BEHAVIORAL.NO_BODY"
    BEHAVIORAL_PARSE_ERROR = "HTML.BEHAVIORAL.PARSE_ERROR"
    BEHAVIORAL_READ_ERROR = "HTML.BEHAVIORAL.READ_ERROR"
    BEHAVIORAL_SKIPPED = "HTML.BEHAVIORAL.SKIPPED"


class CSS:
    """Finding IDs emitted by CSS assessors."""

    # Static assessor.
    MISSING_FILES = "CSS.MISSING_FILES"
    SKIPPED = "CSS.SKIPPED"
    READ_ERROR = "CSS.READ_ERROR"
    BRACES_BALANCED = "CSS.BRACES_BALANCED"
    BRACES_UNBALANCED = "CSS.BRACES_UNBALANCED"
    NO_RULES = "CSS.NO_RULES"
    EVIDENCE = "CSS.EVIDENCE"
    QUALITY_OVERLY_SPECIFIC = "CSS.QUALITY.OVERLY_SPECIFIC"

    # Required assessor.
    REQ_PASS = "CSS.REQ.PASS"
    REQ_FAIL = "CSS.REQ.FAIL"
    REQ_SKIPPED = "CSS.REQ.SKIPPED"
    REQ_MISSING_FILES = "CSS.REQ.MISSING_FILES"
    REQ_READ_ERROR = "CSS.REQ.READ_ERROR"


class JS:
    """Finding IDs emitted by JS assessors."""

    # Static assessor.
    MISSING_FILES = "JS.MISSING_FILES"
    SKIPPED = "JS.SKIPPED"
    READ_ERROR = "JS.READ_ERROR"
    SYNTAX_OK = "JS.SYNTAX_OK"
    SYNTAX_SUSPECT = "JS.SYNTAX_SUSPECT"
    NO_CODE = "JS.NO_CODE"
    EVIDENCE = "JS.EVIDENCE"
    API_EVIDENCE = "JS.API_EVIDENCE"
    QUALITY_GLOBAL_VARIABLES = "JS.QUALITY.GLOBAL_VARIABLES"
    QUALITY_POOR_NAMING = "JS.QUALITY.POOR_NAMING"
    QUALITY_UNUSED_VARIABLES = "JS.QUALITY.UNUSED_VARIABLES"
    QUALITY_UNREACHABLE_CODE = "JS.QUALITY.UNREACHABLE_CODE"
    QUALITY_LACK_OF_MODULARITY = "JS.QUALITY.LACK_OF_MODULARITY"

    # Required assessor.
    REQ_PASS = "JS.REQ.PASS"
    REQ_FAIL = "JS.REQ.FAIL"
    REQ_SKIPPED = "JS.REQ.SKIPPED"
    REQ_MISSING_FILES = "JS.REQ.MISSING_FILES"
    REQ_READ_ERROR = "JS.REQ.READ_ERROR"


class PHP:
    """Finding IDs emitted by PHP assessors."""

    # Static assessor.
    MISSING_FILES = "PHP.MISSING_FILES"
    SKIPPED = "PHP.SKIPPED"
    READ_ERROR = "PHP.READ_ERROR"
    TAG_OK = "PHP.TAG_OK"
    TAG_MISSING = "PHP.TAG_MISSING"
    SYNTAX_OK = "PHP.SYNTAX_OK"
    SYNTAX_SUSPECT = "PHP.SYNTAX_SUSPECT"
    SMOKE = "PHP.SMOKE"
    NO_CODE = "PHP.NO_CODE"
    EVIDENCE = "PHP.EVIDENCE"
    FORM_INJECTION = "PHP.FORM_INJECTION"
    API_EVIDENCE = "PHP.API_EVIDENCE"
    API_ENDPOINT_DETECTED = "PHP.API_ENDPOINT_DETECTED"
    API_METHOD_ROUTING = "PHP.API_METHOD_ROUTING"
    API_INPUT_PARSING = "PHP.API_INPUT_PARSING"
    QUALITY_MIXED_MARKUP = "PHP.QUALITY.MIXED_MARKUP"
    QUALITY_SQL_IN_OUTPUT = "PHP.QUALITY.SQL_IN_OUTPUT"
    SECURITY_UNSANITIZED_INPUT = "PHP.SECURITY.UNSANITIZED_INPUT"
    SECURITY_UNESCAPED_OUTPUT = "PHP.SECURITY.UNESCAPED_OUTPUT"
    SECURITY_NO_PREPARED_STATEMENTS = "PHP.SECURITY.NO_PREPARED_STATEMENTS"
    SECURITY_PREPARED_STATEMENTS_USED = "PHP.SECURITY.PREPARED_STATEMENTS_USED"
    SECURITY_SESSION_NOT_STARTED = "PHP.SECURITY.SESSION_NOT_STARTED"
    SECURITY_SESSION_NOT_REGENERATED = "PHP.SECURITY.SESSION_NOT_REGENERATED"

    # Required assessor.
    REQ_PASS = "PHP.REQ.PASS"
    REQ_FAIL = "PHP.REQ.FAIL"
    REQ_SKIPPED = "PHP.REQ.SKIPPED"
    REQ_MISSING_FILES = "PHP.REQ.MISSING_FILES"
    REQ_READ_ERROR = "PHP.REQ.READ_ERROR"


class SQL:
    """Finding IDs emitted by SQL assessors."""

    # Static assessor.
    MISSING_FILES = "SQL.MISSING_FILES"
    SKIPPED = "SQL.SKIPPED"
    READ_ERROR = "SQL.READ_ERROR"
    STRUCTURE_OK = "SQL.STRUCTURE_OK"
    STRUCTURE_SUSPECT = "SQL.STRUCTURE_SUSPECT"
    NO_SEMICOLONS = "SQL.NO_SEMICOLONS"
    EMPTY = "SQL.EMPTY"
    SQLITE_EXEC = "SQL.SQLITE_EXEC"
    EVIDENCE = "SQL.EVIDENCE"
    QUALITY_SELECT_STAR = "SQL.QUALITY.SELECT_STAR"
    SECURITY_DYNAMIC_SQL = "SQL.SECURITY.DYNAMIC_SQL"
    SECURITY_MISSING_LIMIT = "SQL.SECURITY.MISSING_LIMIT"

    # Required assessor.
    REQ_PASS = "SQL.REQ.PASS"
    REQ_FAIL = "SQL.REQ.FAIL"
    REQ_SKIPPED = "SQL.REQ.SKIPPED"
    REQ_MISSING_FILES = "SQL.REQ.MISSING_FILES"
    REQ_READ_ERROR = "SQL.REQ.READ_ERROR"


class API:
    """Finding IDs emitted by API assessors."""

    # Static assessor.
    MISSING_FILES = "API.MISSING_FILES"
    SKIPPED = "API.SKIPPED"
    EVIDENCE = "API.EVIDENCE"

    # Required assessor.
    REQ_PASS = "API.REQ.PASS"
    REQ_FAIL = "API.REQ.FAIL"
    REQ_SKIPPED = "API.REQ.SKIPPED"
    REQ_MISSING_FILES = "API.REQ.MISSING_FILES"


class CONSISTENCY:
    """Finding IDs emitted by the consistency assessor."""

    CSS_MISSING_HTML_ID = "CONSISTENCY.CSS_MISSING_HTML_ID"
    CSS_MISSING_HTML_CLASS = "CONSISTENCY.CSS_MISSING_HTML_CLASS"
    JS_MISSING_HTML_ID = "CONSISTENCY.JS_MISSING_HTML_ID"
    JS_MISSING_HTML_CLASS = "CONSISTENCY.JS_MISSING_HTML_CLASS"
    MISSING_LINK_TARGET = "CONSISTENCY.MISSING_LINK_TARGET"
    MISSING_FORM_ACTION_TARGET = "CONSISTENCY.MISSING_FORM_ACTION_TARGET"
    FORM_FIELD_UNUSED_IN_PHP = "CONSISTENCY.FORM_FIELD_UNUSED_IN_PHP"
    PHP_EXPECTS_MISSING_FORM_FIELD = "CONSISTENCY.PHP_EXPECTS_MISSING_FORM_FIELD"

    # Cross-file alignment checks.
    PHP_FORM_ALIGNED = "CONSISTENCY.PHP_FORM_ALIGNED"
    PHP_FORM_MISALIGNED = "CONSISTENCY.PHP_FORM_MISALIGNED"
    SQL_APP_ALIGNED = "CONSISTENCY.SQL_APP_ALIGNED"
    SQL_APP_MISALIGNED = "CONSISTENCY.SQL_APP_MISALIGNED"
    API_CLIENT_ALIGNED = "CONSISTENCY.API_CLIENT_ALIGNED"
    API_CLIENT_MISALIGNED = "CONSISTENCY.API_CLIENT_MISALIGNED"


class BROWSER:
    """Finding IDs emitted by the browser assessor."""

    PAGE = "BROWSER.PAGE"
    ERRORS = "BROWSER.ERRORS"
    PERFORMANCE = "BROWSER.PERFORMANCE"
    CAPTURE_FAIL = "BROWSER.CAPTURE_FAIL"

    # Extended browser checks.
    CONSOLE_CLEAN = "BROWSER.CONSOLE_CLEAN"
    CONSOLE_ERRORS_FATAL = "BROWSER.CONSOLE_ERRORS_FATAL"
    NETWORK_ASSETS_OK = "BROWSER.NETWORK_ASSETS_OK"
    NETWORK_ASSETS_FAIL = "BROWSER.NETWORK_ASSETS_FAIL"
    DOM_STRUCTURE_OK = "BROWSER.DOM_STRUCTURE_OK"
    DOM_STRUCTURE_FAIL = "BROWSER.DOM_STRUCTURE_FAIL"
    COMPUTED_STYLE_MATCH = "BROWSER.COMPUTED_STYLE_MATCH"
    COMPUTED_STYLE_MISMATCH = "BROWSER.COMPUTED_STYLE_MISMATCH"
    ACCESSIBLE_TARGETS_OK = "BROWSER.ACCESSIBLE_TARGETS_OK"
    ACCESSIBLE_TARGETS_FAIL = "BROWSER.ACCESSIBLE_TARGETS_FAIL"
    SCREENSHOT_CONSISTENT = "BROWSER.SCREENSHOT_CONSISTENT"


class BEHAVIOUR:
    """Finding IDs used in rationale strings for behavioural evidence."""

    SKIPPED_PROFILE = "BEHAVIOUR.SKIPPED_PROFILE"
    UNEXPECTED_ERROR = "BEHAVIOUR.UNEXPECTED_ERROR"
    PHP_SMOKE_PASS = "BEHAVIOUR.PHP_SMOKE_PASS"
    PHP_SMOKE_FAIL = "BEHAVIOUR.PHP_SMOKE_FAIL"
    PHP_SMOKE_SKIPPED = "BEHAVIOUR.PHP_SMOKE_SKIPPED"
    PHP_SMOKE_TIMEOUT = "BEHAVIOUR.PHP_SMOKE_TIMEOUT"
    PHP_FORM_RUN_PASS = "BEHAVIOUR.PHP_FORM_RUN_PASS"
    PHP_FORM_RUN_FAIL = "BEHAVIOUR.PHP_FORM_RUN_FAIL"
    PHP_FORM_RUN_SKIPPED = "BEHAVIOUR.PHP_FORM_RUN_SKIPPED"
    PHP_FORM_RUN_TIMEOUT = "BEHAVIOUR.PHP_FORM_RUN_TIMEOUT"
    SQL_EXEC_PASS = "BEHAVIOUR.SQL_EXEC_PASS"
    SQL_EXEC_FAIL = "BEHAVIOUR.SQL_EXEC_FAIL"
    SQL_EXEC_SKIPPED = "BEHAVIOUR.SQL_EXEC_SKIPPED"
    SQL_EXEC_TIMEOUT = "BEHAVIOUR.SQL_EXEC_TIMEOUT"
    API_EXEC_PASS = "BEHAVIOUR.API_EXEC_PASS"
    API_EXEC_FAIL = "BEHAVIOUR.API_EXEC_FAIL"
    API_EXEC_SKIPPED = "BEHAVIOUR.API_EXEC_SKIPPED"
    API_EXEC_TIMEOUT = "BEHAVIOUR.API_EXEC_TIMEOUT"
    API_JSON_VALID = "BEHAVIOUR.API_JSON_VALID"
    API_JSON_INVALID = "BEHAVIOUR.API_JSON_INVALID"

    # Calculator behavioural tests.
    CALCULATOR_PASS = "BEHAVIOUR.CALCULATOR_PASS"
    CALCULATOR_FAIL = "BEHAVIOUR.CALCULATOR_FAIL"
    CALCULATOR_PARTIAL = "BEHAVIOUR.CALCULATOR_PARTIAL"
    CALCULATOR_SKIPPED = "BEHAVIOUR.CALCULATOR_SKIPPED"
    HOVER_PASS = "BEHAVIOUR.HOVER_PASS"
    HOVER_FAIL = "BEHAVIOUR.HOVER_FAIL"
    HOVER_SKIPPED = "BEHAVIOUR.HOVER_SKIPPED"
    VIEWPORT_PASS = "BEHAVIOUR.VIEWPORT_PASS"
    VIEWPORT_FAIL = "BEHAVIOUR.VIEWPORT_FAIL"
    VIEWPORT_SKIPPED = "BEHAVIOUR.VIEWPORT_SKIPPED"


class SANDBOX:
    """Finding IDs emitted by the threat scanner."""

    class THREAT:
        SHELL_EXECUTION = "SANDBOX.THREAT.SHELL_EXECUTION"
        FILESYSTEM_ESCAPE = "SANDBOX.THREAT.FILESYSTEM_ESCAPE"
        NETWORK_ACCESS = "SANDBOX.THREAT.NETWORK_ACCESS"
        CODE_INJECTION = "SANDBOX.THREAT.CODE_INJECTION"
        BINARY_INJECTION = "SANDBOX.THREAT.BINARY_INJECTION"
        OBFUSCATION = "SANDBOX.THREAT.OBFUSCATION"
        PROCESS_CONTROL = "SANDBOX.THREAT.PROCESS_CONTROL"
        SYMLINK_ATTACK = "SANDBOX.THREAT.SYMLINK_ATTACK"
        DANGEROUS_JS = "SANDBOX.THREAT.DANGEROUS_JS"


__all__ = [
    "HTML",
    "CSS",
    "JS",
    "PHP",
    "SQL",
    "API",
    "CONSISTENCY",
    "BROWSER",
    "BEHAVIOUR",
    "SANDBOX",
]
